import streamlit as st

st.title("Cryptocurrency Prices")

import requests
import pandas as pd

chosen_symbol = st.selectbox(
    "Choose a cryptocurrency",
    ([
    'BTC',
    'ETH',
    'USDT',
    'XRP',
    'BNB',
    'USDC',
    'SOL',
    'TRX',
    'DOGE',
    'HYPE',
    'LEO',
    'BCH',
    'ADA',
    'XMR',
    'LINK',
    'ZEC',
    'CC',
    'XLM',
    'DAI',
    'M',
    'USD1',
    'LTC',
    'AVAX',
    'HBAR',
    'USDe',
    'SUI',
    'SHIB',
    'PYUSD',
    'TON',
    'CRO',
    'TAO',
    'XAUt',
    'USDG',
    'WLFI',
    'PAXG',
    'MNT',
    'SKY',
    'UNI',
    'DOT',
    'PI',
    'NEAR',
    'OKB',
    'ASTER',
    'PEPE',
    'RLUSD',
    'AAVE',
    'USDD',
    'BGB',
    'ICP',
    'ETC',
    'ONDO',
    'DEXE',
    'KCS',
    'U',
    'ALGO',
    'ATOM',
    'POL',
    'ENA',
    'RENDER',
    'KAS',
    'MORPHO',
    'QNT',
    'WLD',
    'GT',
    'STABLE',
    'APT',
    'ARB',
    'FIL',
    'JST',
    'JUP',
    'FLR',
    'PENGU',
    'VET',
    'XDC',
    'TRUMP',
    'PUMP',
    'NEXO',
    'NIGHT',
    'BONK',
    'CHZ',
    'SIREN',
    'TUSD',
    'CAKE',
    'ZRO',
    'FET',
    'EDGE',
    'VIRTUAL',
    'DASH',
    'EURC',
    'AERO',
    'SEI',
    'FDUSD',
    'VVV',
    'STX',
    'XTZ',
    'H',
    'ZBCN',
    '币安人生',
    'LUNC',
    'ETHFI',
    'MON',
    'INJ',
    'SUN',
    'SPX',
    'CRV',
    'LDO',
    'IMX',
    'GNO',
    'DCR',
    'TIA',
    'NFT',
    'BTT',
    'BSV',
    'CFX',
    'FLOKI',
    'KAIA',
    '2Z',
    'JASMY',
    'SYRUP',
    'PYTH',
    'KITE',
    'GRT',
    'OP',
    'IOTA',
    'AXS',
    'ENS',
    'XCN',
    'COMP',
    'SAND',
    'RAVE',
    'STRK',
    'PENDLE',
    'LIT',
    'THETA',
    'TEL',
    'NEO',
    'RAY',
    'FARTCOIN',
    'GENIUS',
    'SFP',
    'TWT',
    'HNT',
    'MANA',
    'IP',
    'VSN',
    'WIF',
    'XPL',
    'RUNE',
    'CVX',
    'WAL',
    'SKYAI',
    'MX',
    'JTO',
    'GALA',
    'BAT',
    'AB',
    'FF',
    'TRAC',
    'DEEP',
    'CHIP',
    'ZK',
    'A',
    'STG',
    'XEC',
    'AKT',
    'B',
    'GLM',
    'BEAT',
    '1INCH',
    'FLUID',
    'RIVER',
    'DYDX',
    'SENT',
    'S',
    'EGLD',
    'AR',
    'EIGEN',
    'ENJ',
    '0G',
    'CFG',
    'ATH',
    'RSR',
    'MELANIA',
    'CHEEMS',
    'WEMIX',
    'SNX',
    'AWE',
    'GAS',
    'ZEN',
    'APE',
    'LPT',
    'COW',
    'SAFE',
    'KAITO',
    'BEAM',
    'YFI',
    'FTT',
    'ZRX',
    'RVN',
    'SPK',
]),
)

def get_crypto_prices(symbol):
    url = f"https://data.alpaca.markets/v1beta3/crypto/us/bars?symbols={symbol}%2FUSD&timeframe=1Min&limit=1000&sort=asc"
    headers = {"accept": "application/json"}
    response = requests.get(url, headers=headers)
    df = pd.DataFrame(response.json()['bars'][f'{symbol}/USD'])
    df = df[['t','o','h','l','c','n','v','vw']]
    df.columns = [
        'Timestamp',
        'Opening price',
        'High price',
        'Low price',
        'Closing price',
        'Bar volume',
        'Trade count',
        'Volume weighted average price',
    ]
    df[['Opening price','High price','Low price','Closing price','Volume weighted average price']] = \
        df[['Opening price','High price','Low price','Closing price','Volume weighted average price']].round(2)
    df['Timestamp'] = pd.to_datetime(df['Timestamp'])
    return df

df = get_crypto_prices(chosen_symbol)

st.write(df)

column = st.selectbox(
    "Choose a quantity:",
    df.columns
)

st.line_chart(data=df, x="Timestamp", y=column)